language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: B+TepYL7g7xFNTGQ9UyGyXUXi1X7ZNBVRrbtyEVGWSq3tfatVVHgeUB5w+DoF+ip5JEj3m4DXsU9aTRW3W/L3uAapoAoyrGFMJxriYBTsHZ51FqD+nLALCKsSNQKNy6j3wML+BL6bzJbvuYq8+wEMH1CvFCdfjrcrkKkPPGBiYNdy3OB1Mt0+1V33W9LJ8j05AmT7TuZ38XN1PcAmYmjfLdnmbZgpk/dQAEs62ufbGg/MIoYyIyXboLjnbDt17oCEb2BLc1pcuSrGblGhY4wcpcBEgBtugM8/z5VfqmZG4HoTT6uTh6KJ/bqNs3bXa8/SEw7Cfk5jGDHjbAB8g+f+r05u2KdjkJkweFiyv8CZST7r5FgZnPjhZzr5WdXIojchCZiE7YS2TmiKpT0dznpPpGWwGGf0/p8YPWpQ63JEe4akmHtnSZaGgIeEK6kNhtMIDu99GpMYHwJhLEmRrNTgfKoSs4b/3iKd541cazHnpUbh6uzVW4/HvdHOyulTmtimRokmRFg9M7ZHFgXUnfIyjmeha+ZDaEFxQmnLsDb9iP3VlhYK6Oag44wssj2xfs+a5N1SZKHcoXv2edYdVfpu6eqovTFOptUkka6aNe1I36C/aGwsVoWVqQL/u65H+sv6seydiGuGLR6XxwrVuhUutB3J6xUmQ/nN8DkpkoUZpc=
  file:
    - 'attach-ware.js'
    - 'attach-ware.min.js'
  on:
    tags: true
